apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector: # Selects the Pods with labels listed before. Pod must have ALL labels.
    app: hello-world # Send to Pods with this label