# Custom files with settings for the eksctl tool (for easy creation of EKS cluster)
# Must have eksctl tool installed locally.
# Calls CloudFormation scripts to deploy an EKS Cluster
# To run-- 
#   eksctl create cluster -f .\mycluster
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: us-east-2
nodeGroups:
  - name: ng-1
    instanceType: t3.micro # Set EC2 node instances to t3.micro (to save on spend)
    desiredCapacity: 2